title: WiDS Datathon 2020
logo: /images/logo.png
description: 
The WiDS Cambridge Datathon Workshop is an annual workshop preceding the WiDS Cambridge Conference. 
The workshop provide smentorship and training for those interested in participating in the WiDS Datathon Challenge, 
and, more generally, anyone with a strong interest in data science.
theme: jekyll-theme-minimal
